In [1]:
import numpy as np
import os

In [2]:
corpdir = '/fileserver/icdar13/jimbo/processed/TASfeats/Comps'
files = os.listdir(corpdir)

In [3]:
files.sort()
metric = []

In [4]:
files

['027_1.txt',
 '027_2.txt',
 '027_3.txt',
 '027_4.txt',
 '028_1.txt',
 '028_2.txt',
 '028_3.txt',
 '028_4.txt',
 '029_1.txt',
 '029_2.txt',
 '029_3.txt',
 '029_4.txt',
 '030_1.txt',
 '030_2.txt',
 '030_3.txt',
 '030_4.txt',
 '031_1.txt',
 '031_2.txt',
 '031_3.txt',
 '031_4.txt',
 '032_1.txt',
 '032_2.txt',
 '032_3.txt',
 '032_4.txt',
 '033_1.txt',
 '033_2.txt',
 '033_3.txt',
 '033_4.txt',
 '034_1.txt',
 '034_2.txt',
 '034_3.txt',
 '034_4.txt',
 '035_1.txt',
 '035_2.txt',
 '035_3.txt',
 '035_4.txt',
 '036_1.txt',
 '036_2.txt',
 '036_3.txt',
 '036_4.txt',
 '037_1.txt',
 '037_2.txt',
 '037_3.txt',
 '037_4.txt',
 '038_1.txt',
 '038_2.txt',
 '038_3.txt',
 '038_4.txt',
 '039_1.txt',
 '039_2.txt',
 '039_3.txt',
 '039_4.txt',
 '040_1.txt',
 '040_2.txt',
 '040_3.txt',
 '040_4.txt',
 '041_1.txt',
 '041_2.txt',
 '041_3.txt',
 '041_4.txt',
 '042_1.txt',
 '042_2.txt',
 '042_3.txt',
 '042_4.txt',
 '043_1.txt',
 '043_2.txt',
 '043_3.txt',
 '043_4.txt',
 '044_1.txt',
 '044_2.txt',
 '044_3.txt',
 '044_

In [5]:
for filename in files:
    corpfilename = corpdir + "/" + filename
    corpfile = open(corpfilename, 'r').read().splitlines()
    metricline = [np.array([corpline.split(' ')[1] for corpline in corpfile]).astype(np.float32)]
    metric += metricline

In [6]:
metric = np.array(metric)

In [7]:
F = -metric

In [8]:
np.fill_diagonal(F, -1)

In [9]:
F

array([[-1.       , -0.0490867, -0.0540987, ..., -0.0670812, -0.0713386,
        -0.0675054],
       [-0.0490867, -1.       , -0.0500069, ..., -0.0619037, -0.0658001,
        -0.0636483],
       [-0.0540987, -0.0500069, -1.       , ..., -0.0664196, -0.0698018,
        -0.0670775],
       ..., 
       [-0.0670812, -0.0619037, -0.0664196, ..., -1.       , -0.0618494,
        -0.0647121],
       [-0.0713386, -0.0658001, -0.0698018, ..., -0.0618494, -1.       ,
        -0.0507757],
       [-0.0675054, -0.0636483, -0.0670775, ..., -0.0647121, -0.0507757,
        -1.       ]], dtype=float32)

In [10]:
k = 10
maxtop = 7
g = 4

In [11]:
softcorrect = 0
hardcorrect = 0
totalnum = 0

In [12]:
topk = F[0].argsort()[-10:]
topk

array([254,  58, 283, 128, 148, 121,   2, 129,   3,   1])

In [13]:
topk = F[1].argsort()[-10:]
topk

array([  3, 128, 283, 253,   2, 245, 255,   0, 121, 129])

In [14]:
maxtop = 3

In [15]:
softcorrect = 0
hardcorrect = 0
totalnum = 0
for j, i in enumerate(F):
    topk = i.argsort()[-k:]
    # Soft criteria
    if j/g in topk/g:
        softcorrect += 1
    totalnum +=1
    # Hard criteria
    hardsample = sum([1 for jj in (j/g == topk[-maxtop:]/g) if jj])
    if hardsample==maxtop:
        hardcorrect += 1

In [16]:
hardcorrect

18

In [17]:
print "Top %d (soft criteria) = %f" %( k, (softcorrect+0.0) / totalnum )
print "Top %d (hard criteria) = %f" %( k, (hardcorrect+0.0) / totalnum )

Top 10 (soft criteria) = 0.967500
Top 10 (hard criteria) = 0.045000
