In [7]:
import numpy as np
from collections import namedtuple

In [19]:
# purpose. given an author-fragment dictionary-of-dictionaries-of-arrays object,
# pick a random fragment, produce deterministic shingles from that document

class InferenceShingler:
    ShingleSize=namedtuple('ShingleSize', ['rows','cols'])
    
    def __init__(self, img, num_shingles=None, 
                 hskip=None, vskip=None, 
                 shingle_size=ShingleSize(rows=120,cols=120)):
        """ given an image of a document fragment, 
        produce deterministic shingles from that document
        
        Arguments:
            img --
            num_shingles --
            hskip --
            vskip --
            shingle_size -- ROWS, COLS format!!
        """
        self.img = img
        assert num_shingles is not None or (hskip is not None and vskip is not None)
        self.shingle_size = shingle_size
        self.vskip = vskip
        self.hskip = hskip
        
        # TODO: warn if danger of leaving off right or bottom edge
        h_margin = self.img.shape[1] - self.hskip
        if h_margin
        
    def iter_shingles(self):
        for row_i in xrange(0, self.img.shape[0] - self.shingle_size[0], self.vskip):
            for col_j in xrange(0, self.img.shape[1] - self.shingle_size[1], self.hskip):
                end_col = col_j + self.shingle_size[1]
                end_row = row_i + self.shingle_size[0]
                yield self.img[row_i:end_row, col_j:end_col]

In [22]:
#img_coords = np.dstack(np.meshgrid(np.arange(10), np.arange(10,20)))
img = np.arange(100).reshape(10,10)
print img

inf_shin = InferenceShingler(img, hskip=3, vskip=3, shingle_size=(2,2))

for shingle in inf_shin.iter_shingles():
    print shingle

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1]
 [10 11]]
[[ 3  4]
 [13 14]]
[[ 6  7]
 [16 17]]
[[30 31]
 [40 41]]
[[33 34]
 [43 44]]
[[36 37]
 [46 47]]
[[60 61]
 [70 71]]
[[63 64]
 [73 74]]
[[66 67]
 [76 77]]
